const String SERVER_FAILURE_MESSAGE = 'Please try again later .';
const List<String> provinces = [
    'Al Anbar',
    'Al Basrah',
    'Al Muthanna',
    'Al Qadisiyyah',
    'Al Najaf',
    'Erbil',
    'Sulaymaniyah',
    'Babil',
    'Baghdad',
    'DhiQar',
    'Diyala',
    'Dohuk',
    'Karbala',
    'Kirkuk',
    'Maysan',
    'Ninawa',
    'Salah ad Din',
    'Wasit',
  ];
   const List<String> categoryTypes = [
    'Residential',
    'Commercial',
    'Industrial',
    'Agricultural',
    'Land',
    'Apartment',
    'House',
    'Villa',
    'Office',
    'Retail',
    'Warehouse',
    'Farm',
    'Ranch',
    'Plot',
    'Condominium',
    'Hotel',
    'Resort',
    'Restaurant',
    'Garage',
    'Other',
  ];